version: "3.7"

networks:
  monitoring:
    driver: bridge
    external: true

services:
  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager:${ALERT_MANAGER_VERSION:-v0.27.0}
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
      - '--log.level=debug'
    ports:
      - 9093:9093
    networks:
      - monitoring
    restart: unless-stopped
