version: "3.8"

networks:
  monitoring:
    driver: bridge
    external: true

services:
  node-exporter:
    image: prom/node-exporter:{$NODE_EXPORTER_VERSION:-v1.7.0}
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    ports:
      - 9100:9100
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:{PROMETHEUS_VERSION:-v2.50.1}
    user: "1000"
    environment:
      - PUID=1000
      - PGID=1000
    container_name: prometheus
    restart: unless-stopped
    depends_on:
      - node-exporter
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.enable-lifecycle"
    ports:
      - 9090:9090
    networks:
      - monitoring

  thanos-sidecar:
    image: quay.io/thanos/thanos:{THANOS_SIDECAR_VERSION:-v0.34.1}
    volumes:
      - ./thanos/:/etc/thanos
      - ./prometheus:/prometheus
    command:
      - "sidecar"
      - "--tsdb.path=/prometheus"
      - "--prometheus.url=http://prometheus:9090"
      - "--grpc-address=0.0.0.0:10901"
      - "--http-address=0.0.0.0:10902"
      # - '--objstore.config-file=/etc/thanos/bucket_config.yaml'
    container_name: thanos-sidecar
    networks:
      - monitoring
    depends_on:
      - prometheus
    ports:
      - 10901:10901
    restart: unless-stopped


