version: "3.8"

networks:
  monitoring:
    driver: bridge
    external: true

services:
  grafana:
    image: grafana/grafana:${GRAFANA_VERSION:-10.2.4}
    user: "1000"
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana:/var/lib/grafana
    networks:
      - monitoring

  thanos-querier:
    image: quay.io/thanos/thanos:${THANOS_QUERIER_VERSION:-v0.34.1}
    command:
      - "query"
      - "--grpc-address=0.0.0.0:10901"
      - "--http-address=0.0.0.0:10902"
      - "--query.replica-label=replica"
      - "--store=0.0.0.0:10901"
    ports:
      - 10902:10902
    networks:
      - monitoring
    restart: unless-stopped
