global:
  scrape_interval: 1m
  external_labels:
    cluster: "demo-cluster"

alerting:
  alertmanagers:
    - static_configs:
        - targets: [alert-manager:9093]

rule_files:
  - "rules.yml"

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]      
