groups:
- name: DummyAlertForTesting
  rules:
  - alert: DummyAlert
    expr: vector(1)
    for: 1m
    labels:
      severity: dummy
    annotations:
      summary: "This is a dummy alert"
      description: "This alert is triggered to verify that Alertmanager is working properly."
